# Generated by Django 4.0.6 on 2022-07-16 15:33

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=server.models.ProjectDocument.get_upload_folder),
        ),
    ]
