# Generated by Django 4.0.6 on 2022-07-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_program_entities_program_expected_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='server.program'),
        ),
    ]
