# Generated by Django 4.0.6 on 2022-07-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_projectdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
