# Generated by Django 4.0.5 on 2022-07-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_projectdocument_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chief',
            name='is_program_chief',
        ),
        migrations.RemoveField(
            model_name='chief',
            name='name',
        ),
        migrations.AddField(
            model_name='chief',
            name='chief_type',
            field=models.TextField(choices=[('project_chief', 'Jefe de Proyecto'), ('program_chief', 'Jefe de Programa'), ('human_res', 'Recursos Humanos'), ('economy', 'Economia'), ('vicedec_inv_postgr', 'Vicedecano de Investigacion y Postgrado')], default='project_chief', max_length=255),
        ),
    ]
