# Generated by Django 4.0.6 on 2022-07-12 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_project_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='server.program'),
        ),
    ]
