# Generated by Django 4.0.6 on 2022-07-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_project_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='full_name',
            new_name='name',
        ),
    ]
