# Generated by Django 4.0.6 on 2022-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_rename_full_name_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='end_date',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='ptype',
            field=models.TextField(choices=[('nac', 'Nacional'), ('sec', 'Sectorial'), ('ter', 'Territorial')], default='nac'),
        ),
        migrations.AddField(
            model_name='program',
            name='start_date',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
