# Generated by Django 4.0.6 on 2022-07-15 13:05

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_program_end_date_program_ptype_program_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('file', models.FileField(null=True, upload_to=server.models.ProgramDocument.get_upload_folder)),
            ],
        ),
    ]
