# Generated by Django 4.0.6 on 2022-07-15 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_programdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdocument',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='server.program'),
        ),
    ]
