# Generated by Django 4.0.5 on 2022-07-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='chief',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='server.chief'),
        ),
        migrations.AlterField(
            model_name='project',
            name='chief',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='server.chief'),
        ),
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='server.program'),
        ),
    ]
