# Generated by Django 4.0.5 on 2022-07-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_program_chief_alter_project_chief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pj_type',
            field=models.TextField(choices=[('pap', 'Proyectos Asociados a Programas'), ('pnap', 'Proyectos No Asociados a Programas')], default='pap', max_length=255),
        ),
    ]
