# Generated by Django 4.0.6 on 2022-07-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_program_chief_alter_program_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='money',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='pj_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='user_clients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
