# Generated by Django 4.0.6 on 2022-07-15 13:39

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_program_money_program_pj_amount_program_user_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=server.models.ProgramDocument.get_upload_folder),
        ),
    ]
