# Generated by Django 4.0.5 on 2022-07-07 22:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0011_alter_project_chief_alter_project_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chief',
            new_name='Member',
        ),
    ]
