# Generated by Django 4.0.6 on 2022-07-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_alter_project_main_entity_alter_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdocument',
            name='name',
        ),
        migrations.AddField(
            model_name='documentgroup',
            name='dtype',
            field=models.CharField(choices=[('other', 'Otro'), ('dpac', 'Desglose del presupuesto del año en curso'), ('mca', 'Anexo 15 Modelo de certificación de actividades'), ('isp', 'Anexo 13 Informe semestral del proyecto'), ('ict', 'Informe científico técnico'), ('dapiscca', 'Dictamen de aprobación del informe semestral por el CCA'), ('dgeri', 'Dictamen del Grupo de Expertos sobre los resultados y el Informe de la Etapa'), ('mnig', 'Anexo 16 Modelo de Notificación de Ingresos/Gastos'), ('bcpr', 'Base de cálculo para el pago por remuneración'), ('acpp', 'Acta de conformidad de los participantes del proyecto'), ('cpr', 'Certificación para el pago de la remuneración'), ('cpie', 'Anexo 8. Certifico para el pago de los investigadores externos')], default='other', max_length=512),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='dtype',
            field=models.CharField(choices=[('other', 'Otro'), ('profile', 'Perfil'), ('contract', 'Contract'), ('rsjf', 'Resolución de nombramiento del jefe de proyecto'), ('cidef', 'Compatibilización con los intereses de la Defensa'), ('roap', 'Resolución oficial de aprobación del proyecto'), ('dapcca', 'Dictamen de aprobación del proyecto por el CCA'), ('dpddp', 'Documentos de planificación del diseño y desarrollo del producto'), ('csbie', 'Certifico del salario básico de los investigadores externos'), ('fciie', 'Fotos escaneadas del carné de identidad de los investigadores')], default='other', max_length=512),
        ),
    ]
