# Generated by Django 4.0.6 on 2022-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_alter_programdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdocument',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
