# Generated by Django 4.0.5 on 2022-07-08 16:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0012_rename_chief_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Chief',
        ),
    ]
