# Generated by Django 4.0.5 on 2022-07-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_rename_member_chief'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('c_id', models.TextField(max_length=11)),
            ],
            options={
                'verbose_name': 'Members',
            },
        ),
    ]
