# Generated by Django 4.0.6 on 2022-07-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_groupdocument_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentgroup',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
