# Generated by Django 4.0.5 on 2022-07-15 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_alter_programdocument_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pj_id',
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='financing',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='program_code',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='project_classification',
            field=models.TextField(choices=[('i_bas', 'De Investigación Básica'), ('i_d', 'Aplicada y de Desarrollo'), ('inn', 'Innovación')], default='i_bas', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='project_code',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='pj_type',
            field=models.TextField(choices=[('papn', 'Proyectos Asociados a Programas Nacional'), ('paps', 'Proyectos Asociados a Programas Sectorial'), ('papt', 'Proyectos Asociados a Programas Territorial'), ('pnap_di', 'Proyectos No Asociados a Programas Demanda Interna'), ('pnap_de', 'Proyectos No Asociados a Programas Demanda Externa')], default='papt', max_length=255),
        ),
    ]
