# Generated by Django 4.0.5 on 2022-07-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member'},
        ),
    ]
