# Generated by Django 4.0.5 on 2022-07-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
    ]
