# Generated by Django 4.0.6 on 2022-08-01 13:13

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_alter_groupdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdocument',
            name='file',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=server.models.GroupDocument.get_upload_folder),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to=server.models.ProjectDocument.get_upload_folder),
        ),
    ]
