# Generated by Django 4.0.5 on 2022-07-15 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_member_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_code',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='program',
            name='money',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
