# Generated by Django 4.1 on 2022-09-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_alter_groupdocument_file_alter_projectdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chief',
            name='chief_type',
            field=models.TextField(choices=[('project_program_both_chief', 'Jefe de Proyecto/ Programa / Ambos'), ('human_resources', 'Recursos Humanos'), ('economy', 'Economia'), ('vicedec_inv_postgr', 'Vicedecano de Investigacion y Postgrado')], default='human_resources', max_length=255),
        ),
    ]
