# Generated by Django 4.1 on 2022-09-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_alter_chief_chief_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='program_code',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
