# Generated by Django 3.2.12 on 2022-10-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_alter_project_program_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=256, upload_to='Documentación')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
