# Generated by Django 4.0.6 on 2022-10-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='project',
        ),
        migrations.AddField(
            model_name='member',
            name='projects',
            field=models.ManyToManyField(related_name='members', to='server.project'),
        ),
    ]
