# Generated by Django 4.0.6 on 2022-10-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_remove_member_project_member_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='c_id',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
