# Generated by Django 4.0.6 on 2022-10-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0022_alter_member_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='m_type',
            field=models.TextField(choices=[('in', 'Interno'), ('out', 'Externo')], default='in', max_length=255),
        ),
    ]
