# Generated by Django 4.1 on 2022-10-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_project_notes_alter_program_strategics_sectors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='pj_amount',
        ),
        migrations.AlterField(
            model_name='chief',
            name='chief_type',
            field=models.TextField(choices=[('project_program_both_chief', 'Jefe de Proyecto/ Programa'), ('human_resources', 'Recursos Humanos'), ('economy', 'Economia'), ('vicedec_inv_postgr', 'Vicedecano de Investigacion y Postgrado')], default='human_resources', max_length=255),
        ),
    ]
