# Generated by Django 3.2.12 on 2022-10-29 13:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0026_remove_program_pj_amount_alter_chief_chief_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramDocumentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('dtype', models.CharField(choices=[('other', 'Otro'), ('dpac', 'Desglose del presupuesto del año en curso'), ('mca', 'Anexo 15 Modelo de certificación de actividades'), ('isp', 'Anexo 13 Informe semestral del proyecto'), ('ict', 'Informe científico técnico'), ('dapiscca', 'Dictamen de aprobación del informe semestral por el CCA'), ('dgeri', 'Dictamen del Grupo de Expertos sobre los resultados y el Informe de la Etapa'), ('mnig', 'Anexo 16 Modelo de Notificación de Ingresos/Gastos'), ('bcpr', 'Base de cálculo para el pago por remuneración'), ('acpp', 'Acta de conformidad de los participantes del proyecto'), ('cpr', 'Certificación para el pago de la remuneración'), ('cpie', 'Anexo 8. Certifico para el pago de los investigadores externos')], default='other', max_length=512)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_groups', to='server.program')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramGroupDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=256, null=True, upload_to=server.models.ProgramGroupDocument.get_upload_folder)),
                ('date', models.DateField(default=datetime.date.today)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='server.programdocumentgroup')),
            ],
        ),
    ]
