# Generated by Django 3.2.12 on 2022-10-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0027_programdocumentgroup_programgroupdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='programdocument',
            name='dtype',
            field=models.CharField(choices=[('other', 'Otro'), ('profile', 'Perfil'), ('contract', 'Contract'), ('rsjf', 'Resolución de nombramiento del jefe de proyecto'), ('cidef', 'Compatibilización con los intereses de la Defensa'), ('roap', 'Resolución oficial de aprobación del proyecto'), ('dapcca', 'Dictamen de aprobación del proyecto por el CCA'), ('dpddp', 'Documentos de planificación del diseño y desarrollo del producto'), ('csbie', 'Certifico del salario básico de los investigadores externos'), ('fciie', 'Fotos escaneadas del carné de identidad de los investigadores')], default='other', max_length=512),
        ),
    ]
