# Generated by Django 4.1.3 on 2022-11-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0028_programdocument_dtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='dtype',
            field=models.CharField(choices=[('other', 'Otro'), ('profile', 'Perfil'), ('contract', 'Contract'), ('rsjf', 'Resolución de nombramiento del equipo de dirección'), ('dap', 'Documento de aprobación del programa'), ('daeg', 'Documento de aprobación de la entidad gestora'), ('cidef', 'Compatibilización con los intereses de la Defensa'), ('dpddp', 'Documentos de planificación del diseño y desarrollo del producto'), ('csbie', 'Certifico del salario básico de los investigadores externos'), ('fciie', 'Fotos escaneadas del carné de identidad de los investigadores')], default='other', max_length=512),
        ),
        migrations.AlterField(
            model_name='programdocumentgroup',
            name='dtype',
            field=models.CharField(choices=[('other', 'Otro'), ('dpac', 'Desglose del presupuesto del año en curso'), ('mca', 'Anexo 15 Modelo de certificación de actividades'), ('rdlc', 'Resultados de la convocatoria'), ('rpe', 'Relación de proyectos en ejecucion'), ('arge', 'Actas de las reuniones del grupo de expertos'), ('iar', 'Informe anual de resultados del programa'), ('ifp', 'Informe final del programa'), ('bcpr', 'Base de cálculo para el pago por remuneración'), ('acpp', 'Acta de conformidad de los participantes del programa'), ('cpr', 'Certificación para el pago de la remuneración'), ('cpie', 'Anexo 8. Certifico para el pago de los investigadores externos')], default='other', max_length=512),
        ),
        migrations.AlterField(
            model_name='project',
            name='pj_type',
            field=models.TextField(choices=[('papn', 'Proyectos Asociados a Programas Nacional'), ('paps', 'Proyectos Asociados a Programas Sectorial'), ('papt', 'Proyectos Asociados a Programas Territorial'), ('pnap_pe', 'Proyectos No Asociados a Programas (PE)'), ('pnap_pne', 'Proyectos No Asociados a Programas (PNE)'), ('pnap_pdl', 'Proyectos No Asociados a Programas (PDL)'), ('pnap_prci', 'Proyectos No Asociados a Programas (PRCI)'), ('pnap_pi', 'Proyectos No Asociados a Programas (PI)')], default='papt', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='dtype',
            field=models.CharField(choices=[('other', 'Otro'), ('profile', 'Perfil'), ('contract', 'Contract'), ('rsjf', 'Resolución de nombramiento del jefe de proyecto'), ('cidef', 'Compatibilización con los intereses de la Defensa'), ('roap', 'Resolución oficial de aprobación del proyecto'), ('dapp', 'Dictamen de aprobación del proyecto por el programa'), ('dapcca', 'Dictamen de aprobación del proyecto por el CCA'), ('dpddp', 'Documentos de planificación del diseño y desarrollo del producto'), ('csbie', 'Certifico del salario básico de los investigadores externos'), ('fciie', 'Fotos escaneadas del carné de identidad de los investigadores')], default='other', max_length=512),
        ),
    ]
