# Generated by Django 4.1 on 2022-11-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0029_project_status_alter_programdocument_dtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chief',
            name='faculty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='programdocument',
            name='dtype',
            field=models.CharField(choices=[('other', 'Otro'), ('profile', 'Perfil'), ('contract', 'Contrato'), ('rsjf', 'Resolución de nombramiento del equipo de dirección'), ('dap', 'Documento de aprobación del programa'), ('daeg', 'Documento de aprobación de la entidad gestora'), ('cidef', 'Compatibilización con los intereses de la Defensa'), ('dpddp', 'Documentos de planificación del diseño y desarrollo del producto'), ('csbie', 'Certifico del salario básico de los investigadores externos'), ('fciie', 'Fotos escaneadas del carné de identidad de los investigadores')], default='other', max_length=512),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='dtype',
            field=models.CharField(choices=[('other', 'Otro'), ('profile', 'Perfil'), ('contract', 'Contrato'), ('rsjf', 'Resolución de nombramiento del jefe de proyecto'), ('cidef', 'Compatibilización con los intereses de la Defensa'), ('roap', 'Resolución oficial de aprobación del proyecto'), ('dapp', 'Dictamen de aprobación del proyecto por el programa'), ('dapcca', 'Dictamen de aprobación del proyecto por el CCA'), ('dpddp', 'Documentos de planificación del diseño y desarrollo del producto'), ('csbie', 'Certifico del salario básico de los investigadores externos'), ('fciie', 'Fotos escaneadas del carné de identidad de los investigadores')], default='other', max_length=512),
        ),
    ]
