# Generated by Django 4.1 on 2022-11-26 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0030_chief_faculty_alter_programdocument_dtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chief',
            name='faculty',
        ),
    ]
