# Generated by Django 4.1 on 2022-11-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0034_alter_chief_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chief',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
